### ISSUE TITLE
feat: 내 대결 목록 장르 필터링

### ISSUE THREAD

**Issue by dazzel3** [prgrms-web-devcourse/Team-6Jeans-Hype-FE#259]
## 📃 작업 내용

- 내 대결 목록 장르 필터링 추가해야함

**Comment by NamJwong** [comment]
이거 참여한 대결 리스트 페이지인가요?? 

맞다면 https://github.com/prgrms-web-devcourse/Team-6Jeans-Hype-FE/issues/166 요 이슈랑 엮어서 https://github.com/prgrms-web-devcourse/Team-6Jeans-Hype-FE/pull/328 여기에 올렸습니다 !!

**Comment by dazzel3** [comment]
맞습니다! 이슈 닫겠습니다
