### ISSUE TITLE
fix: 추천 글 상세 페이지 한마디 토글 버튼 클릭시 블록 잡히는 문제

### ISSUE THREAD

**Issue by Park-min-hyoung** [prgrms-web-devcourse/Team-6Jeans-Hype-FE#286]
## 📃 작업 내용

ContentHeader에서  -webkit-tap-highlight-color: transparent !important; 추가해야 함

**Comment by dazzel3** [comment]
이거 전역으로 적용할 예정이라 나중에 한 번에 처리 하겠습니다

**Comment by Park-min-hyoung** [comment]
나중에 전역으로 적용할 예정이므로 close
